// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX5yokWnYgoTOF_HGz3o9SS7QMC9cmKNg',
    appId: '1:659321249820:web:95d09d9d11959545d63fd9',
    messagingSenderId: '659321249820',
    projectId: 'examnotesfirebase',
    authDomain: 'examnotesfirebase.firebaseapp.com',
    databaseURL: 'https://examnotesfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'examnotesfirebase.appspot.com',
    measurementId: 'G-QVXLCZGDRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwS1wwb4qGiNcQY6_XBJMDsMIKLH8ccJM',
    appId: '1:659321249820:android:d6a31aad19fbfa3ed63fd9',
    messagingSenderId: '659321249820',
    projectId: 'examnotesfirebase',
    databaseURL: 'https://examnotesfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'examnotesfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsMre6_AISiemW61U6ug3kCXiNrOY18V8',
    appId: '1:659321249820:ios:bc4ba620249c1ae9d63fd9',
    messagingSenderId: '659321249820',
    projectId: 'examnotesfirebase',
    databaseURL: 'https://examnotesfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'examnotesfirebase.appspot.com',
    iosBundleId: 'com.example.examNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsMre6_AISiemW61U6ug3kCXiNrOY18V8',
    appId: '1:659321249820:ios:ae9fe2f30d56261dd63fd9',
    messagingSenderId: '659321249820',
    projectId: 'examnotesfirebase',
    databaseURL: 'https://examnotesfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'examnotesfirebase.appspot.com',
    iosBundleId: 'com.example.examNotes.RunnerTests',
  );
}
